export type FieldConfig = {
  name: string;
  label: string;
  type: 'text' | 'textarea' | 'tags' | 'number' | 'checkbox' | 'select' | 'url' | 'email';
  placeholder?: string;
  options?: Array<{ label: string; value: string }>;
};

export const publicationStatusOptions = [
  { label: 'Draft', value: 'draft' },
  { label: 'Published', value: 'published' },
  { label: 'Archived', value: 'archived' },
];

const singleMediaIdHint = 'Paste a media ID from the Media Library.';
const multiMediaIdHint = 'Paste comma-separated media IDs from the Media Library.';

export const singletonFields = {
  profile: [
    { name: 'fullName', label: 'Full name', type: 'text' },
    { name: 'preferredName', label: 'Preferred name', type: 'text' },
    { name: 'professionalTitle', label: 'Professional title', type: 'text' },
    { name: 'rotatingTitles', label: 'Rotating titles', type: 'tags' },
    { name: 'shortIntroduction', label: 'Short introduction', type: 'textarea' },
    { name: 'professionalSummary', label: 'Professional summary', type: 'textarea' },
    { name: 'careerObjective', label: 'Career objective', type: 'textarea' },
    { name: 'generalLocation', label: 'General location', type: 'text' },
    {
      name: 'availability',
      label: 'Availability',
      type: 'select',
      options: [
        { label: 'Open to work', value: 'open_to_work' },
        { label: 'Selective', value: 'selective' },
        { label: 'Not available', value: 'not_available' },
      ],
    },
    { name: 'profileImageId', label: 'Profile image media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'publicEmail', label: 'Public email', type: 'email' },
    { name: 'publicPhone', label: 'Public phone', type: 'text' },
    { name: 'publicationStatus', label: 'Publication status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  privateDetails: [
    { name: 'privateEmail', label: 'Private email', type: 'email' },
    { name: 'privatePhone', label: 'Private phone', type: 'text' },
    { name: 'fullAddress', label: 'Full address', type: 'textarea' },
    { name: 'dateOfBirth', label: 'Date of birth', type: 'text' },
    { name: 'parentOrGuardian', label: 'Parent or guardian', type: 'text' },
    { name: 'gender', label: 'Gender', type: 'text' },
    { name: 'nationality', label: 'Nationality', type: 'text' },
    { name: 'city', label: 'City', type: 'text' },
    { name: 'state', label: 'State', type: 'text' },
    { name: 'country', label: 'Country', type: 'text' },
    { name: 'emailIsPublic', label: 'Email is public', type: 'checkbox' },
    { name: 'phoneIsPublic', label: 'Phone is public', type: 'checkbox' },
  ] satisfies FieldConfig[],
  hero: [
    { name: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { name: 'heading', label: 'Heading', type: 'text' },
    { name: 'subheading', label: 'Subheading', type: 'textarea' },
    { name: 'highlights', label: 'Highlights', type: 'tags' },
    { name: 'ctaPrimaryLabel', label: 'Primary CTA label', type: 'text' },
    { name: 'ctaPrimaryHref', label: 'Primary CTA link', type: 'text' },
    { name: 'ctaSecondaryLabel', label: 'Secondary CTA label', type: 'text' },
    { name: 'ctaSecondaryHref', label: 'Secondary CTA link', type: 'text' },
    { name: 'heroImageId', label: 'Hero image media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'publicationStatus', label: 'Publication status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  about: [
    { name: 'fullBiography', label: 'Biography', type: 'textarea' },
    { name: 'preferredEmploymentArea', label: 'Preferred employment area', type: 'text' },
    { name: 'currentLocation', label: 'Current location', type: 'text' },
    { name: 'availabilityLabel', label: 'Availability label', type: 'text' },
    { name: 'keyStrengths', label: 'Key strengths', type: 'tags' },
    { name: 'aboutImageId', label: 'About image media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'publicationStatus', label: 'Publication status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  siteSettings: [
    { name: 'siteName', label: 'Site name', type: 'text' },
    { name: 'siteTagline', label: 'Site tagline', type: 'text' },
    { name: 'logoId', label: 'Logo media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'faviconId', label: 'Favicon media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'openGraphImageId', label: 'Open Graph image media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'accentColor', label: 'Accent color', type: 'text' },
    { name: 'secondaryAccentColor', label: 'Secondary accent', type: 'text' },
    { name: 'footerText', label: 'Footer text', type: 'textarea' },
    { name: 'enableDarkTheme', label: 'Enable dark theme', type: 'checkbox' },
    { name: 'maintenanceMode', label: 'Maintenance mode', type: 'checkbox' },
  ] satisfies FieldConfig[],
  seo: [
    { name: 'defaultTitle', label: 'Default title', type: 'text' },
    { name: 'defaultDescription', label: 'Default description', type: 'textarea' },
    { name: 'defaultKeywords', label: 'Default keywords', type: 'tags' },
    { name: 'defaultOpenGraphImageId', label: 'Default Open Graph media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'siteUrl', label: 'Site URL', type: 'url' },
  ] satisfies FieldConfig[],
};

export const collectionFields = {
  experience: [
    { name: 'jobTitle', label: 'Job title', type: 'text' },
    { name: 'organisation', label: 'Organisation', type: 'text' },
    { name: 'employmentType', label: 'Employment type', type: 'text' },
    { name: 'location', label: 'Location', type: 'text' },
    { name: 'startDate', label: 'Start date', type: 'text' },
    { name: 'endDate', label: 'End date', type: 'text' },
    {
      name: 'datePrecision',
      label: 'Date precision',
      type: 'select',
      options: [
        { label: 'Exact date', value: 'exact' },
        { label: 'Month', value: 'month' },
        { label: 'Year', value: 'year' },
        { label: 'Duration', value: 'duration' },
      ],
    },
    { name: 'approximateDuration', label: 'Approximate duration', type: 'text' },
    { name: 'isCurrentPosition', label: 'Current position', type: 'checkbox' },
    { name: 'professionalSummary', label: 'Summary', type: 'textarea' },
    { name: 'responsibilities', label: 'Responsibilities', type: 'tags' },
    { name: 'keyAchievements', label: 'Achievements', type: 'tags' },
    { name: 'researchAreas', label: 'Research areas', type: 'tags' },
    { name: 'toolsUsed', label: 'Tools used', type: 'tags' },
    { name: 'organisationLogoId', label: 'Organisation logo media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  education: [
    { name: 'institution', label: 'Institution', type: 'text' },
    { name: 'qualification', label: 'Qualification', type: 'text' },
    { name: 'fieldOfStudy', label: 'Field of study', type: 'text' },
    { name: 'startDate', label: 'Start date', type: 'text' },
    { name: 'completionDate', label: 'Completion date', type: 'text' },
    { name: 'grade', label: 'Grade', type: 'text' },
    { name: 'percentage', label: 'Percentage', type: 'text' },
    { name: 'location', label: 'Location', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea' },
    { name: 'subjects', label: 'Subjects', type: 'tags' },
    { name: 'academicAchievements', label: 'Academic achievements', type: 'tags' },
    { name: 'institutionLogoId', label: 'Institution logo media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'supportingDocumentId', label: 'Supporting document media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  training: [
    { name: 'organisation', label: 'Organisation', type: 'text' },
    { name: 'trainingTitle', label: 'Training title', type: 'text' },
    { name: 'department', label: 'Department', type: 'text' },
    { name: 'trainingType', label: 'Training type', type: 'text' },
    { name: 'location', label: 'Location', type: 'text' },
    { name: 'startDate', label: 'Start date', type: 'text' },
    { name: 'endDate', label: 'End date', type: 'text' },
    { name: 'duration', label: 'Duration', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea' },
    { name: 'responsibilities', label: 'Responsibilities', type: 'tags' },
    { name: 'learningOutcomes', label: 'Learning outcomes', type: 'tags' },
    { name: 'skillsDeveloped', label: 'Skills developed', type: 'tags' },
    { name: 'certificateImageId', label: 'Certificate image media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'certificatePdfId', label: 'Certificate PDF media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'organisationLogoId', label: 'Organisation logo media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  projects: [
    { name: 'title', label: 'Project title', type: 'text' },
    { name: 'slug', label: 'Slug', type: 'text' },
    { name: 'shortDescription', label: 'Short description', type: 'textarea' },
    { name: 'fullDescription', label: 'Full description', type: 'textarea' },
    { name: 'category', label: 'Category', type: 'text' },
    { name: 'duration', label: 'Duration', type: 'text' },
    { name: 'startDate', label: 'Start date', type: 'text' },
    { name: 'completionDate', label: 'Completion date', type: 'text' },
    { name: 'status', label: 'Project status', type: 'text' },
    { name: 'objectives', label: 'Objectives', type: 'tags' },
    { name: 'problemStatement', label: 'Problem statement', type: 'textarea' },
    { name: 'methodology', label: 'Methodology', type: 'textarea' },
    { name: 'toolsAndTechnologies', label: 'Tools and technologies', type: 'tags' },
    { name: 'responsibilities', label: 'Responsibilities', type: 'tags' },
    { name: 'mainFeatures', label: 'Main features', type: 'tags' },
    { name: 'challenges', label: 'Challenges', type: 'tags' },
    { name: 'solutions', label: 'Solutions', type: 'tags' },
    { name: 'outcomes', label: 'Outcomes', type: 'tags' },
    { name: 'learningOutcomes', label: 'Learning outcomes', type: 'tags' },
    { name: 'thumbnailId', label: 'Thumbnail media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'galleryImageIds', label: 'Gallery media IDs', type: 'tags', placeholder: multiMediaIdHint },
    { name: 'supportingDocumentIds', label: 'Supporting document IDs', type: 'tags', placeholder: multiMediaIdHint },
    { name: 'githubUrl', label: 'GitHub URL', type: 'url' },
    { name: 'liveUrl', label: 'Live URL', type: 'url' },
    { name: 'caseStudyUrl', label: 'Case-study URL', type: 'url' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  languages: [
    { name: 'name', label: 'Language', type: 'text' },
    {
      name: 'readingProficiency',
      label: 'Reading',
      type: 'select',
      options: [
        { label: 'Unselected', value: '' },
        { label: 'Basic', value: 'basic' },
        { label: 'Conversational', value: 'conversational' },
        { label: 'Professional', value: 'professional' },
        { label: 'Fluent', value: 'fluent' },
        { label: 'Native', value: 'native' },
      ],
    },
    {
      name: 'writingProficiency',
      label: 'Writing',
      type: 'select',
      options: [
        { label: 'Unselected', value: '' },
        { label: 'Basic', value: 'basic' },
        { label: 'Conversational', value: 'conversational' },
        { label: 'Professional', value: 'professional' },
        { label: 'Fluent', value: 'fluent' },
        { label: 'Native', value: 'native' },
      ],
    },
    {
      name: 'speakingProficiency',
      label: 'Speaking',
      type: 'select',
      options: [
        { label: 'Unselected', value: '' },
        { label: 'Basic', value: 'basic' },
        { label: 'Conversational', value: 'conversational' },
        { label: 'Professional', value: 'professional' },
        { label: 'Fluent', value: 'fluent' },
        { label: 'Native', value: 'native' },
      ],
    },
    { name: 'isNative', label: 'Native language', type: 'checkbox' },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  interests: [
    { name: 'title', label: 'Title', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea' },
    { name: 'icon', label: 'Icon', type: 'text' },
    { name: 'imageId', label: 'Interest image media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  socialLinks: [
    { name: 'label', label: 'Label', type: 'text' },
    { name: 'url', label: 'URL', type: 'url' },
    { name: 'icon', label: 'Icon', type: 'text' },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  navigation: [
    { name: 'label', label: 'Label', type: 'text' },
    { name: 'href', label: 'Href', type: 'text' },
    { name: 'opensInNewTab', label: 'Open in new tab', type: 'checkbox' },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  skillCategories: [
    { name: 'name', label: 'Category name', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea' },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  skills: [
    { name: 'name', label: 'Skill name', type: 'text' },
    { name: 'categoryId', label: 'Category', type: 'select' },
    { name: 'description', label: 'Description', type: 'textarea' },
    {
      name: 'proficiencyLevel',
      label: 'Proficiency',
      type: 'select',
      options: [
        { label: 'Unselected', value: '' },
        { label: 'Beginner', value: 'beginner' },
        { label: 'Familiar', value: 'familiar' },
        { label: 'Intermediate', value: 'intermediate' },
        { label: 'Advanced', value: 'advanced' },
        { label: 'Expert', value: 'expert' },
      ],
    },
    { name: 'proficiencyPercentage', label: 'Proficiency percentage', type: 'number' },
    { name: 'yearsOfExperience', label: 'Years of experience', type: 'number' },
    { name: 'icon', label: 'Icon', type: 'text' },
    { name: 'logoId', label: 'Skill logo media ID', type: 'text', placeholder: singleMediaIdHint },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
  personalSkills: [
    { name: 'title', label: 'Title', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea' },
    { name: 'displayOrder', label: 'Display order', type: 'number' },
    { name: 'publicationStatus', label: 'Status', type: 'select', options: publicationStatusOptions },
  ] satisfies FieldConfig[],
};
