export const ankitaSeedData = {
  professionalHeading:
    'Research Analyst | Pharmacy Graduate | Quality Control and Pharmaceutical Software',
  rotatingTitles: [
    'Research Analyst',
    'Pharmacy Graduate',
    'Quality Control Industrial Trainee',
    'Pharmaceutical Software Learner',
    'Data Analysis Tools User',
  ],
  heroHeading: 'Ankita Singh',
  heroSubheading:
    'Detail-oriented pharmacy graduate and current Research Analyst with hands-on quality control training, pharmaceutical software exposure, and a disciplined approach to accurate research work.',
  heroHighlights: [
    'Current Research Analyst at Royal Research',
    '2 years and 3 months of research analysis experience',
    'B.Pharm graduate with QC training at Glenmark Pharmaceuticals',
  ],
  shortIntroduction:
    'Dedicated pharmacy graduate with research analysis experience, QC training, and practical familiarity with pharmaceutical software tools.',
  professionalSummary:
    'Ankita Singh is a detail-oriented Research Analyst at Royal Research and a pharmacy graduate with hands-on industrial training in quality control. Her experience includes structured research analysis, data-driven evaluation, report accuracy, and collaboration with cross-functional teams while using pharmaceutical and data analysis tools.',
  careerObjective:
    'To secure a research or quality-focused role in a reputed pharmaceutical organization where strong analytical skills, disciplined work ethic, and accuracy under pressure can support dependable outcomes.',
  fullBiography:
    'Ankita Singh is a pharmacy graduate and current Research Analyst based in Sankrail, Howrah, West Bengal. She brings 2 years and 3 months of research analysis experience at Royal Research, practical industrial exposure from the Quality Control department at Glenmark Pharmaceuticals, and working knowledge of pharmaceutical software and data analysis tools. Her professional approach is careful, adaptable, collaborative, and focused on accurate delivery under pressure.',
  preferredEmploymentArea:
    'Research analysis, pharmaceutical quality control, and data-supported evaluation',
  currentLocation: 'Sankrail, Howrah, West Bengal, India',
  keyStrengths: [
    'Strong adaptability to new concepts and evolving work environments',
    'Positive attitude with effective time management',
    'Collaborative team player with a hardworking and flexible approach',
    'Accuracy-focused work under pressure',
  ],
  experience: [
    {
      jobTitle: 'Research Analyst',
      organisation: 'Royal Research',
      employmentType: 'Current role',
      location: 'India',
      isCurrentPosition: true,
      approximateDuration: '2 years and 3 months',
      datePrecision: 'duration',
      professionalSummary:
        'Conducts research analysis and data-driven evaluation to support organized, accurate, and timely reporting.',
      responsibilities: [
        'Conduct research analysis and data-driven evaluation across 15-20 projects per month.',
        'Apply structured methodologies to maintain accuracy, consistency, and timely delivery of research outcomes.',
        'Collaborate with cross-functional teams of 4-6 members to streamline reporting and reduce errors.',
      ],
      keyAchievements: [
        'Improved report turnaround time by approximately 20% through structured research workflows.',
        'Helped reduce reporting errors by approximately 15% through collaborative process discipline.',
      ],
      researchAreas: ['Research analysis', 'Data-driven evaluation', 'Report quality'],
      toolsUsed: ['MS Office', 'SPSS', 'NVivo', 'MySQL', 'Orange Data Mining'],
      featured: true,
      publicationStatus: 'published',
      displayOrder: 0,
    },
  ],
  education: [
    {
      institution: 'Hygia Institute of Pharmaceutical Education and Research',
      qualification: 'Bachelor of Pharmacy',
      fieldOfStudy: 'Pharmacy',
      startDate: '2019',
      completionDate: '2023',
      datePrecision: 'year',
      description: 'Affiliated to Veer Bahadur Singh Purvanchal University.',
      publicationStatus: 'published',
      displayOrder: 0,
    },
    {
      institution: 'Veer Bahadur Singh Purvanchal University',
      qualification: 'Bachelor of Science',
      startDate: '2017',
      completionDate: '2020',
      datePrecision: 'year',
      publicationStatus: 'published',
      displayOrder: 1,
    },
    {
      institution: 'MMD Public School',
      qualification: 'Intermediate, Class XII',
      completionDate: '2017',
      datePrecision: 'year',
      publicationStatus: 'published',
      displayOrder: 2,
    },
    {
      institution: 'MMD Public School',
      qualification: 'High School, Class X',
      completionDate: '2015',
      datePrecision: 'year',
      publicationStatus: 'published',
      displayOrder: 3,
    },
  ],
  training: [
    {
      organisation: 'Glenmark Pharmaceuticals',
      trainingTitle: 'Industrial Training Placement',
      department: 'Quality Control Department',
      trainingType: 'Industrial Training',
      location: 'Baddi, Himachal Pradesh, India',
      startDate: '2022-02',
      endDate: '2022-03',
      duration: '45 days',
      description:
        'Completed a 45-day industrial training program in the Quality Control department with exposure to pharmaceutical sample analysis, documentation, and GMP-focused practices.',
      responsibilities: [
        'Handled 30-50 pharmaceutical samples for quality-focused analysis during training.',
        'Supported documentation accuracy and adherence to pharmaceutical compliance standards.',
      ],
      learningOutcomes: [
        'Practical exposure to quality testing procedures.',
        'Improved understanding of GMP practices and pharmaceutical compliance expectations.',
      ],
      skillsDeveloped: [
        'Quality Control',
        'GMP awareness',
        'Sample handling',
        'Documentation accuracy',
      ],
      publicationStatus: 'published',
      displayOrder: 0,
    },
  ],
  skillCategories: [
    { name: 'Office and productivity', displayOrder: 0 },
    { name: 'Database', displayOrder: 1 },
    { name: 'Data analysis', displayOrder: 2 },
    { name: 'Bioinformatics and scientific research', displayOrder: 3 },
    { name: 'Pharmaceutical and scientific software', displayOrder: 4 },
  ],
  skills: [
    { name: 'Microsoft Office', categoryName: 'Office and productivity', displayOrder: 0 },
    { name: 'MySQL', categoryName: 'Database', displayOrder: 1 },
    { name: 'SPSS', categoryName: 'Data analysis', displayOrder: 2 },
    { name: 'NVivo', categoryName: 'Data analysis', displayOrder: 3 },
    { name: 'Orange Data Mining', categoryName: 'Data analysis', displayOrder: 4 },
    { name: 'BLAST', categoryName: 'Bioinformatics and scientific research', displayOrder: 5 },
    { name: 'Marg ERP', categoryName: 'Pharmaceutical and scientific software', displayOrder: 6 },
    { name: 'ChemDraw', categoryName: 'Pharmaceutical and scientific software', displayOrder: 7 },
  ],
  personalSkills: [
    'Strong adaptability',
    'Positive attitude',
    'Effective time management',
    'Collaborative teamwork',
    'Hardworking approach',
    'Flexible work style',
    'Accuracy under pressure',
    'Disciplined work ethic',
  ],
  languages: [
    {
      name: 'Hindi',
      readingProficiency: 'fluent',
      writingProficiency: 'fluent',
      speakingProficiency: 'fluent',
      isNative: true,
      displayOrder: 0,
    },
    {
      name: 'English',
      readingProficiency: 'professional',
      writingProficiency: 'professional',
      speakingProficiency: 'professional',
      displayOrder: 1,
    },
  ],
  interests: [
    { title: 'Interacting with people', displayOrder: 0, icon: 'MessagesSquare' },
    { title: 'Watching films', displayOrder: 1, icon: 'Clapperboard' },
    { title: 'Listening to music', displayOrder: 2, icon: 'Headphones' },
    { title: 'Exercise', displayOrder: 3, icon: 'HeartPulse' },
  ],
  project: {
    title: 'Pharmaceutical Software Project',
    slug: 'pharmaceutical-software-project',
    shortDescription:
      'Three-month project focused on Marg ERP and ChemDraw for pharmaceutical workflows.',
    fullDescription:
      'A three-month pharmaceutical software project focused on learning and applying Marg ERP for pharmaceutical data management and ChemDraw for chemical structure drawing.',
    category: 'Pharmaceutical software',
    duration: '3 months',
    datePrecision: 'duration',
    toolsAndTechnologies: ['Marg ERP', 'ChemDraw'],
    objectives: [
      'Build practical familiarity with pharmaceutical data management software.',
      'Use chemical structure drawing tools in a pharmaceutical learning context.',
    ],
    learningOutcomes: [
      'Practical familiarity with Marg ERP for pharmaceutical data management.',
      'Applied ChemDraw for chemical structure drawing.',
    ],
    publicationStatus: 'published',
    featured: true,
    displayOrder: 0,
  },
  navigation: [
    { label: 'Home', href: '/', displayOrder: 0 },
    { label: 'About', href: '/about', displayOrder: 1 },
    { label: 'Experience', href: '/experience', displayOrder: 2 },
    { label: 'Skills', href: '/skills', displayOrder: 3 },
    { label: 'Projects', href: '/projects', displayOrder: 4 },
    { label: 'Resume', href: '/resume', displayOrder: 5 },
    { label: 'Contact', href: '/contact', displayOrder: 6 },
  ],
};
