export const ankitaSeedData = {
  professionalHeading:
    'Research Analyst | Pharmacy Graduate | Pharmaceutical and Data Analysis Professional',
  rotatingTitles: [
    'Research Analyst',
    'Pharmacy Graduate',
    'Pharmaceutical Research Professional',
    'Quality Control Trainee',
    'Data Analysis Software User',
  ],
  heroHeading: 'Research Analyst and Pharmacy Graduate focused on quality-driven pharmaceutical work.',
  heroSubheading:
    'Ankita Singh combines pharmacy education, research-analysis experience, and practical software skills to support careful, reliable, and well-organised work in pharmaceutical environments.',
  heroHighlights: [
    '2 years and 3 months of research-analysis experience',
    'Bachelor of Pharmacy graduate',
    'Quality Control industrial training at Glenmark Pharmaceuticals',
  ],
  shortIntroduction:
    'Organised, punctual, and quality-focused professional preparing for responsible opportunities in reputable pharmaceutical organisations.',
  professionalSummary:
    'Ankita Singh is a hardworking and highly organised professional with experience as a Research Analyst and a Bachelor of Pharmacy background. She is comfortable working under pressure, values punctuality and quality, and brings practical exposure to pharmaceutical training and research-oriented software tools.',
  careerObjective:
    'To contribute responsibly within a reputable pharmaceutical organisation, continue building practical experience, and deliver dependable, quality-focused work across research, analysis, and quality systems.',
  fullBiography:
    'Ankita Singh is a pharmacy graduate and research-analysis professional with an interest in responsible, quality-led work. Her background combines academic training in pharmaceutical education, professional research experience, and hands-on exposure to quality control processes. She is recognised for being organised, punctual, adaptable, and committed to delivering strong work even in high-pressure settings.',
  preferredEmploymentArea: 'Pharmaceutical research, quality operations, and analysis support',
  keyStrengths: [
    'Quality-focused working style',
    'Time management and punctuality',
    'Adaptability and positive attitude',
    'Collaborative teamwork',
  ],
  experience: [
    {
      jobTitle: 'Research Analyst',
      organisation: 'Royal Research',
      approximateDuration: '2 years and 3 months',
      datePrecision: 'duration',
      professionalSummary:
        'Held a Research Analyst role with a focus on dependable execution and organised work habits.',
      responsibilities: [],
      keyAchievements: [],
      researchAreas: [],
      toolsUsed: [],
      featured: true,
      publicationStatus: 'published',
      displayOrder: 0,
    },
  ],
  education: [
    {
      institution: 'Hygia Institute of Pharmaceutical Education and Research',
      qualification: 'Bachelor of Pharmacy',
      fieldOfStudy: 'Pharmacy',
      startDate: '2019',
      completionDate: '2023',
      datePrecision: 'year',
      publicationStatus: 'published',
      displayOrder: 0,
    },
    {
      institution: 'Veer Bahadur Singh Purvanchal University',
      qualification: 'Bachelor of Science',
      startDate: '2017',
      completionDate: '2020',
      datePrecision: 'year',
      publicationStatus: 'published',
      displayOrder: 1,
    },
    {
      institution: 'MMD Public School',
      qualification: 'Intermediate, Class XII',
      completionDate: '2017',
      datePrecision: 'year',
      publicationStatus: 'published',
      displayOrder: 2,
    },
    {
      institution: 'MMD Public School',
      qualification: 'High School, Class X',
      completionDate: '2015',
      datePrecision: 'year',
      publicationStatus: 'published',
      displayOrder: 3,
    },
  ],
  training: [
    {
      organisation: 'Glenmark Pharmaceuticals',
      trainingTitle: 'Industrial Training Placement',
      department: 'Quality Control Department',
      trainingType: 'Industrial Training',
      location: 'Himachal Pradesh, India',
      startDate: '2022-02',
      endDate: '2022-03',
      duration: '45 days',
      description:
        'Completed a 45-day industrial training placement within the Quality Control Department at Glenmark Pharmaceuticals.',
      responsibilities: [],
      learningOutcomes: [],
      skillsDeveloped: [],
      publicationStatus: 'published',
      displayOrder: 0,
    },
  ],
  skillCategories: [
    { name: 'Office and productivity', displayOrder: 0 },
    { name: 'Database', displayOrder: 1 },
    { name: 'Data analysis and qualitative research', displayOrder: 2 },
    { name: 'Bioinformatics and scientific research', displayOrder: 3 },
    { name: 'Pharmaceutical and scientific software', displayOrder: 4 },
  ],
  skills: [
    { name: 'Microsoft Office', categoryName: 'Office and productivity', displayOrder: 0 },
    { name: 'MySQL', categoryName: 'Database', displayOrder: 1 },
    { name: 'SPSS', categoryName: 'Data analysis and qualitative research', displayOrder: 2 },
    { name: 'NVivo', categoryName: 'Data analysis and qualitative research', displayOrder: 3 },
    { name: 'Orange', categoryName: 'Data analysis and qualitative research', displayOrder: 4 },
    { name: 'BLAST', categoryName: 'Bioinformatics and scientific research', displayOrder: 5 },
    { name: 'Marg Software', categoryName: 'Pharmaceutical and scientific software', displayOrder: 6 },
    { name: 'ChemDraw', categoryName: 'Pharmaceutical and scientific software', displayOrder: 7 },
  ],
  personalSkills: [
    'Hardworking',
    'Team-oriented',
    'Smart working',
    'Flexible',
    'Positive attitude',
    'Time management',
    'Organised',
    'Punctual',
    'Works well under pressure',
    'Committed to quality',
  ],
  languages: [
    { name: 'Hindi', displayOrder: 0 },
    { name: 'English', displayOrder: 1 },
  ],
  interests: [
    { title: 'Interacting with people', displayOrder: 0, icon: 'MessagesSquare' },
    { title: 'Watching films', displayOrder: 1, icon: 'Clapperboard' },
    { title: 'Listening to music', displayOrder: 2, icon: 'Headphones' },
    { title: 'Exercise', displayOrder: 3, icon: 'HeartPulse' },
  ],
  project: {
    title: 'Pharmaceutical Software Project',
    slug: 'pharmaceutical-software-project',
    shortDescription: 'Learning project focused on Marg software and ChemDraw usage.',
    fullDescription:
      'A three-month learning project centred on building familiarity with Marg software and ChemDraw in a pharmaceutical context.',
    duration: '3 months',
    datePrecision: 'duration',
    toolsAndTechnologies: ['Marg Software', 'ChemDraw'],
    learningOutcomes: ['Practical familiarity with pharmaceutical software usage'],
    publicationStatus: 'published',
    featured: true,
    displayOrder: 0,
  },
  navigation: [
    { label: 'Home', href: '/', displayOrder: 0 },
    { label: 'About', href: '/about', displayOrder: 1 },
    { label: 'Experience', href: '/experience', displayOrder: 2 },
    { label: 'Education', href: '/education', displayOrder: 3 },
    { label: 'Training', href: '/training', displayOrder: 4 },
    { label: 'Projects', href: '/projects', displayOrder: 5 },
    { label: 'Resume', href: '/resume', displayOrder: 6 },
    { label: 'Contact', href: '/contact', displayOrder: 7 },
  ],
};
